name: Push pipeline
on: [push]
jobs:
  Compile-And-Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: Create docker image
        uses: actions/build-docker-image@v2
        with:
          docker-image: 'node:14'
          docker-build-args:
            - "--build-arg'
            - 'NODE_ENV=production'
            - '--build-arg'
            - 'NODE_VERSION=14'
